name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        # Note: GitHub Packages for Python requires some setup
        # For now, we'll just build and store artifacts
        echo "Package built successfully"
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: github-package-distributions
        path: dist/